In [63]:
import pandas as pd
arquivo1 = r"C:\Users\isave\OneDrive\Área de Trabalho\projeto_dados\ESTABELECIMENTO.csv"
arquivo2 = r"C:\Users\isave\OneDrive\Área de Trabalho\projeto_dados\CNAE.csv"
arquivo3 = r"C:\Users\isave\OneDrive\Área de Trabalho\projeto_dados\MUNICIPIOS.csv"


df_est = pd.read_csv(arquivo1, encoding="utf-8-sig", sep=",")
df_cnae = pd.read_csv(arquivo2, sep=",", encoding="utf-8-sig")
df_municipios = pd.read_csv(arquivo3, encoding="utf-8-sig", sep=",")

In [ ]:
#Verificando a tabela Estabelecimento
df_est.head()

,RaizCNPj,NumeroEstabelecimento,DigitoVerificadorCNPJ,TipoEstabelecimento,NomeFantasia,SituacaoCadastral,DataSituacao,CodigoMotivoSituacao,CidadeExterior,CodigoPais,...,CodigoMunicipio,DDDTelefone1,Telefone1,DDDTelefone2,Telefone2,DDDFax,Fax,Email,SituacaoEspecial,DataSituacaoEspacial
0,26894280,1,12,1,NaN,4,20210316,63,NaN,NaN,...,5897,21.0,26034011.0,NaN,NaN,NaN,NaN,DAVID.LASSO@GMAIL.COM,NaN,NaN
1,26894291,1,0,1,M.W. CONSTRUCOES,8,20240208,1,NaN,NaN,...,733,98.0,87842041.0,NaN,NaN,NaN,NaN,RAIMUNDO_SILVA66@HOTMAIL.COM,NaN,NaN
2,26895411,1,86,1,CONFECCAO LIMA,8,20170312,1,NaN,NaN,...,9373,62.0,81163521.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26897293,1,45,1,NaN,4,20210212,63,NaN,NaN,...,9373,62.0,93667318.0,NaN,NaN,NaN,NaN,fabijapinha@hotmail.com,NaN,NaN
4,26898307,1,45,1,NaN,8,20170407,1,NaN,NaN,...,5049,35.0,84346082.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
#Verificando a tabela do CNAE
df_cnae.head()

,CodigoCNAE,Cnae_descricao,Especificidades,Complementos,detalhamento_adicional,Observacao
0,111301,Cultivo de arroz,NaN,NaN,NaN,NaN
1,111302,Cultivo de milho,NaN,NaN,NaN,NaN
2,111303,Cultivo de trigo,NaN,NaN,NaN,NaN
3,111399,Cultivo de outros cereais não especificados an...,NaN,NaN,NaN,NaN
4,112101,Cultivo de algodão herbáceo,NaN,NaN,NaN,NaN

In [59]:
#Verificando a tabela dos municipios
df_municipios.head()

   CodigoMunicipio            NomeMunicipio
0                1            GUAJARA-MIRIM
1                2  ALTO ALEGRE DOS PARECIS
2                3              PORTO VELHO
3                4                  BURITIS
4                5                JI-PARANA

In [54]:
#Colunas
print("Colunas da tabela estabelecimento: \n ") 
df_est.columns

Colunas da tabela estabelecimento:

Index(['RaizCNPj', 'NumeroEstabelecimento', 'DigitoVerificadorCNPJ',
       'TipoEstabelecimento', 'NomeFantasia', 'SituacaoCadastral',
       'DataSituacao', 'CodigoMotivoSituacao', 'CidadeExterior', 'CodigoPais',
       'DataInicioAtividade', 'CNAEPrincipal', 'CNAESecundarias',
       'TipoLogradouro', 'Logradouro', 'NumeroEndereco', 'Complemento',
       'Bairro', 'CEP', 'UF', 'CodigoMunicipio', 'DDDTelefone1', 'Telefone1',
       'DDDTelefone2', 'Telefone2', 'DDDFax', 'Fax', 'Email',
       'SituacaoEspecial', 'DataSituacaoEspacial'],
      dtype='str')

In [68]:
print("Colunas da tabela CNAE: \n ") 
df_cnae.columns

Colunas da tabela CNAE:

Index(['CodigoCNAE', 'Cnae_descricao ', 'Especificidades', 'Complementos',
       'detalhamento_adicional', 'Observacao'],
      dtype='str')

In [67]:
print("Colunas da tabela Municipios: \n ") 
df_municipios.columns

Colunas da tabela Municipios:

Index(['CodigoMunicipio', 'NomeMunicipio'], dtype='str')

In [80]:
print("Detalhamento Estabelecimento: \n ")
df_est.info()

Detalhamento Estabelecimento:

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   raizcnpj               50000 non-null  int64
 1   numeroestabelecimento  50000 non-null  int64
 2   digitoverificadorcnpj  50000 non-null  int64
 3   tipoestabelecimento    50000 non-null  int64
 4   nomefantasia           20849 non-null  str
 5   situacaocadastral      50000 non-null  int64
 6   datasituacao           50000 non-null  str
 7   codigomotivosituacao   50000 non-null  int64
 8   cidadeexterior         54 non-null     str
 9   codigopais             90 non-null     float64
 10  datainicioatividade    50000 non-null  int64
 11  cnaeprincipal          50000 non-null  int64
 12  cnaesecundarias        28336 non-null  str
 13  tipologradouro         49910 non-null  str
 14  logradouro             50000 non-null  str
 15  numeroendereco         50000 non-null  str
 16  complemento            21152 non-null  str
 17  bairro                 49999 non-null  str
 18  cep                    49910 non-null  float64
 19  uf                     50000 non-null  str
 20  codigomunicipio        50000 non-null  int64
 21  dddtelefone1           49908 non-null  float64
 22  telefone1              49908 non-null  float64
 23  dddtelefone2           2945 non-null   float64
 24  telefone2              2926 non-null   float64
 25  dddfax                 2039 non-null   float64
 26  fax                    2042 non-null   float64
 27  email                  38221 non-null  str
 28  situacaoespecial       19 non-null     str
 29  datasituacaoespacial   19 non-null     float64
dtypes: float64(9), int64(9), str(12)
memory usage: 11.4 MB

In [81]:
print("Detalhamento CNAE: \n ")
df_cnae.info()

Detalhamento CNAE:

<class 'pandas.DataFrame'>
RangeIndex: 1359 entries, 0 to 1358
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CodigoCNAE              1359 non-null   int64
 1   Cnae_descricao          1359 non-null   str
 2   Especificidades         97 non-null     str
 3   Complementos            23 non-null     str
 4   detalhamento_adicional  5 non-null      str
 5   Observacao              1 non-null      str
dtypes: int64(1), str(5)
memory usage: 63.8 KB

In [82]:
print("Detalhamento Municipios: \n ")
df_municipios.info()

Detalhamento Municipios:

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CodigoMunicipio  5572 non-null   int64
 1   NomeMunicipio    5572 non-null   str
dtypes: int64(1), str(1)
memory usage: 87.2 KB

In [86]:
#Criei uma função pra limpar as colunas pra evitar erros
def limpar_colunas(df):
    df.columns = df.columns.str.strip()
    return df

df_est = limpar_colunas(df_est)
df_cnae = limpar_colunas(df_cnae)
df_municipios = limpar_colunas(df_municipios)

In [87]:
#Nova analise das colunas
print(df_est.columns)
print(df_cnae.columns)
print(df_municipios.columns)

Index(['raizcnpj', 'numeroestabelecimento', 'digitoverificadorcnpj',
       'tipoestabelecimento', 'nomefantasia', 'situacaocadastral',
       'datasituacao', 'codigomotivosituacao', 'cidadeexterior', 'codigopais',
       'datainicioatividade', 'cnaeprincipal', 'cnaesecundarias',
       'tipologradouro', 'logradouro', 'numeroendereco', 'complemento',
       'bairro', 'cep', 'uf', 'codigomunicipio', 'dddtelefone1', 'telefone1',
       'dddtelefone2', 'telefone2', 'dddfax', 'fax', 'email',
       'situacaoespecial', 'datasituacaoespacial'],
      dtype='str')
Index(['codigocnae', 'cnae_descricao', 'especificidades', 'complementos',
       'detalhamento_adicional', 'observacao'],
      dtype='str')
Index(['codigomunicipio', 'nomemunicipio'], dtype='str')

In [96]:
#Convertendo os dados das colunas
df_est["cnaeprincipal"] = pd.to_numeric(df_est["cnaeprincipal"], errors="coerce")
df_cnae["codigocnae"] = pd.to_numeric(df_cnae["codigocnae"], errors="coerce")
df_est["codigomunicipio"] = pd.to_numeric(df_est["codigomunicipio"], errors="coerce")
df_municipios["codigomunicipio"] = pd.to_numeric(df_municipios["codigomunicipio"], errors="coerce")

df_est["datainicioatividade"] = pd.to_datetime(
    df_est["datainicioatividade"], format="%Y%m%d", errors="coerce"
)

In [100]:
print(df_est["datainicioatividade"].head())

0   2017-01-18
1   2017-01-18
2   2017-01-18
3   2017-01-18
4   2017-01-18
Name: datainicioatividade, dtype: datetime64[us]

In [ ]:
#Verificando os valores 
for col in ['cnaeprincipal', 'codigomunicipio', 'datainicioatividade']:
    print(f"Coluna: {col}")
    print(f" - Tipo: {df_est[col].dtype}")
    print(f" - Valores não convertidos (NaN/NaT): {df_est[col].isna().sum()}")
    print(f" - Alguns valores:\n{df_est[col].head()}")
    print("\n")

Coluna: cnaeprincipal
 - Tipo: int64
 - Valores não convertidos (NaN/NaT): 0
 - Alguns valores:
0    4724500
1    4212000
2    8230001
3    9602501
4    4771704
Name: cnaeprincipal, dtype: int64


Coluna: codigomunicipio
 - Tipo: int64
 - Valores não convertidos (NaN/NaT): 0
 - Alguns valores:
0    5897
1     733
2    9373
3    9373
4    5049
Name: codigomunicipio, dtype: int64


Coluna: datainicioatividade
 - Tipo: datetime64[us]
 - Valores não convertidos (NaN/NaT): 0
 - Alguns valores:
0   2017-01-18
1   2017-01-18
2   2017-01-18
3   2017-01-18
4   2017-01-18
Name: datainicioatividade, dtype: datetime64[us]

In [ ]:
#Join 
df = df_est.merge(
    df_cnae[["codigocnae", "cnae_descricao"]],
    left_on="cnaeprincipal",
    right_on="codigocnae",
    how="left"
)

df = df.merge(
    df_municipios[["codigomunicipio", "nomemunicipio"]],
    on="codigomunicipio",
    how="left"
)

In [106]:
#Traduzir situação cadastral
map_situacao = {
    1: "NULA",
    2: "ATIVA",
    3: "SUSPENSA",
    4: "INAPTA",
    8: "BAIXADA"
}

df["situacao"] = df["situacaocadastral"].map(map_situacao)
df["situacao"].value_counts()

situacao
BAIXADA     20796
ATIVA       18947
INAPTA      10140
SUSPENSA       63
NULA           54
Name: count, dtype: int64

In [107]:
#Filtrar setor de alimentação
palavras = [
    "restaurante", "lanchonete", "bar", "padaria",
    "aliment", "bebida", "pizzaria", "café", "buffet"
]

padrao = "|".join(palavras)

df_food = df[
    df["cnae_descricao"].fillna("").str.lower().str.contains(padrao)
]

In [110]:
#Verificação de empresas ativas
ativas = df_food[df_food["situacaocadastral"] == 2]
print(len(ativas))

1994

In [117]:
#Crescimento mais ou menos presente 
segmentos = df_food["cnae_descricao"].value_counts()

print("Mais presentes:\n")
print(segmentos.head(10))

print("\nMenos presentes: \n")
print(segmentos.tail(10), "\n")

Mais presentes:

cnae_descricao
Lanchonetes                                                                                                                       1274
Fornecimento de alimentos preparados preponderantemente para consumo domiciliar                                                    893
Comércio varejista de bebidas                                                                                                      891
Restaurantes e similares                                                                                                           789
Bares e outros estabelecimentos especializados em servir bebidas                                                                   763
Serviços ambulantes de alimentação                                                                                                 759
Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente     509
Fabricação de produtos de padaria e confeitaria com predominância de produção própria                                              324
Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação                                             294
Padaria e confeitaria com predominância de revenda                                                                                 260
Name: count, dtype: int64

Menos presentes:

cnae_descricao
Fabricação de alimentos para animais                                                          5
Manutenção e reparação de embarcações para esporte e lazer                                    4
Comércio varejista de embarcações e outros veículos recreativos; peças e acessórios           4
Fabricação de máquinas e equipamentos para as indústrias de alimentos                         2
Comércio atacadista de bebidas com atividade de fracionamento e acondicionamento associada    2
Comércio atacadista de massas alimentícias                                                    2
Fabricação de outras bebidas não-alcoólicas não especificadas anteriormente                   2
Construção de embarcações para uso comercial e para usos especiais                            1
Comércio atacadista de café torrado                                                           1
Comércio atacadista de café em grão                                                           1
Name: count, dtype: int64

In [119]:
#Crescimento ao longo do tempo
crescimento = (
    df_food["datainicioatividade"]
    .dt.year
    .value_counts()
    .sort_index()
)

print(crescimento)

datainicioatividade
2014       1
2015       1
2016      68
2017    7253
Name: count, dtype: int64

In [ ]:
# Motivos de empresas baixadas/inaptas

problemas = df_food[
    df_food["situacaocadastral"].isin([4, 8])
]

motivos = (
    problemas["codigomotivosituacao"] 
    .value_counts()
)

print(motivos.head(10))

SyntaxError: invalid syntax (1081842981.py, line 8)