In [51]:
import pandas as pd
arquivo1 = r"C:\Users\isave\OneDrive\Área de Trabalho\projeto_dados\ESTABELECIMENTO.csv"
arquivo2 = r"C:\Users\isave\OneDrive\Área de Trabalho\projeto_dados\CNAE.csv"
arquivo3 = r"C:\Users\isave\OneDrive\Área de Trabalho\projeto_dados\MUNICIPIOS.csv"


df_est = pd.read_csv(arquivo1, encoding="utf-8-sig", sep=",")
df_cnae = pd.read_csv(arquivo2, sep=";", encoding="latin1")
df_municipios = pd.read_csv(arquivo3, encoding="utf-8-sig", sep=",")

In [ ]:
#Verificando a tabela Estabelecimento
df_est.head()

,RaizCNPj,NumeroEstabelecimento,DigitoVerificadorCNPJ,TipoEstabelecimento,NomeFantasia,SituacaoCadastral,DataSituacao,CodigoMotivoSituacao,CidadeExterior,CodigoPais,...,CodigoMunicipio,DDDTelefone1,Telefone1,DDDTelefone2,Telefone2,DDDFax,Fax,Email,SituacaoEspecial,DataSituacaoEspacial
0,26894280,1,12,1,NaN,4,20210316,63,NaN,NaN,...,5897,21.0,26034011.0,NaN,NaN,NaN,NaN,DAVID.LASSO@GMAIL.COM,NaN,NaN
1,26894291,1,0,1,M.W. CONSTRUCOES,8,20240208,1,NaN,NaN,...,733,98.0,87842041.0,NaN,NaN,NaN,NaN,RAIMUNDO_SILVA66@HOTMAIL.COM,NaN,NaN
2,26895411,1,86,1,CONFECCAO LIMA,8,20170312,1,NaN,NaN,...,9373,62.0,81163521.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26897293,1,45,1,NaN,4,20210212,63,NaN,NaN,...,9373,62.0,93667318.0,NaN,NaN,NaN,NaN,fabijapinha@hotmail.com,NaN,NaN
4,26898307,1,45,1,NaN,8,20170407,1,NaN,NaN,...,5049,35.0,84346082.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
#Verificando a tabela do CNAE
df_cnae.head()

   0111301                                   Cultivo de arroz
0   111302                                   Cultivo de milho
1   111303                                   Cultivo de trigo
2   111399  Cultivo de outros cereais não especificados an...
3   112101                        Cultivo de algodão herbáceo
4   112102                                    Cultivo de juta

In [53]:
#Verificando a tabela dos municipios
df_municipios.head()

             0001;"GUAJARA-MIRIM"
0  0002;"ALTO ALEGRE DOS PARECIS"
1              0003;"PORTO VELHO"
2                  0004;"BURITIS"
3                0005;"JI-PARANA"
4              0006;"CHUPINGUAIA"

In [54]:
#Colunas
print("Colunas da tabela estabelecimento: \n ") 
df_est.columns

Colunas da tabela estabelecimento:

Index(['RaizCNPj', 'NumeroEstabelecimento', 'DigitoVerificadorCNPJ',
       'TipoEstabelecimento', 'NomeFantasia', 'SituacaoCadastral',
       'DataSituacao', 'CodigoMotivoSituacao', 'CidadeExterior', 'CodigoPais',
       'DataInicioAtividade', 'CNAEPrincipal', 'CNAESecundarias',
       'TipoLogradouro', 'Logradouro', 'NumeroEndereco', 'Complemento',
       'Bairro', 'CEP', 'UF', 'CodigoMunicipio', 'DDDTelefone1', 'Telefone1',
       'DDDTelefone2', 'Telefone2', 'DDDFax', 'Fax', 'Email',
       'SituacaoEspecial', 'DataSituacaoEspacial'],
      dtype='str')

In [55]:
print("Colunas da tabela CNAE: \n ") 
df_cnae.columns

Colunas da tabela CNAE:

Index(['0111301', 'Cultivo de arroz'], dtype='str')

In [ ]:
print("Colunas da tabela Municipios: \n ") 
df_municipios